services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: dnote
      POSTGRES_PASSWORD: dnote
      POSTGRES_DB: dnote
    volumes:
      - ./dnote_data:/var/lib/postgresql/data
    restart: always

  dnote:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        tarballUrl: https://github.com/dnote/dnote/releases/download/server-v2.1.1/dnote_server_2.1.1_linux_arm64.tar.gz
    environment:
      GO_ENV: PRODUCTION
      DBSkipSSL: "true"
      DBHost: postgres
      DBPort: 5432
      DBName: dnote
      DBUser: dnote
      DBPassword: dnote
      WebURL: localhost:3333
      OnPremises: "true"
      SmtpHost:
      SmtpPort:
      SmtpUsername:
      SmtpPassword:
      DisableRegistration: "false"
    ports:
      - 3333:3000
    depends_on:
      - postgres
    restart: always
