---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Home Laboratory"
subtitle: "Digital Abode"
logo: "assets/icons/owl_logo.png"
icon: "assests/icons/icon-any.png" # Optional icon

header: true
footer: false

# Optional theme customization
# Nord theme inspired from - https://github.com/thermatico/homer-nord
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#2E3440"
    highlight-secondary: "#4C566A"
    highlight-hover: "#81A1C1"
    background: "#3B4252"
    card-background: "#2E3440"
    text: "#D8DEE9"
    text-header: "#D8DEE9"
    text-title: "#81A1C1"
    text-subtitle: "#81A1C1"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#BF616A"
        
    # colors from Nord theme: https://github.com/arcticicestudio/nord

# Optional message
#message:
  #url: https://b4bz.io
  #style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  #title: "Demo !"
  #icon: "fa fa-grin"
  #content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Edit Config"
    icon: "far fa-edit"
    url: "https://vscode.example.com/?folder=/config/homer"
    target: "_blank" # optional html a tag target attribute

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
# Place the icons in "assets/tools/"
services:
  - name: "Cloud"
    icon: "fas fa-cloud"
    items:
      - name: "Bitwarden"
        logo: "assets/tools/bitwarden.png"
        subtitle: "Password Manager"
        tag: "passwords"
        url: "https://passwords.example.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.png"
        subtitle: "Cloud Solution"
        tag: "cloud"
        url: "https://cloud.example.com/"
        target: "_blank"

  - name: "Notes"
    icon: "fas fa-sticky-note"
    items:
      - name: "Joplin"
        logo: "assets/tools/joplin.png"
        subtitle: "Markdown-based Note Editor"
        tag: "notes"
        url: "https://notes.example.com/"
        target: "_blank"
      - name: "Vikunja"
        logo: "assets/tools/vikunja.png"
        subtitle: "Feature-rich Task Management"
        tag: "project management"
        url: "https://tasks.example.com/"
        target: "_blank"
      - name: "Mealie"
        logo: "assets/tools/mealie.png"
        subtitle: "Pantry and Recipe Management"
        tag: "recipes"
        url: "https://recipes.example.com/"
        target: "_blank" 
  
  - name: "Repositories"
    icon: "fas fa-archive"
    items:
      - name: "Paperless"
        logo: "assets/tools/paperless.png"
        subtitle: "Documents Repository"
        tag: "documents"
        url: "https://paperless.example.com/"
        target: "_blank"
      - name: "Calibre-Web"
        logo: "assets/tools/calibre-web.png"
        subtitle: "Ebook Library"
        tag: "ebooks"
        url: "https://ebooks.example.com/"
        target: "_blank"
      - name: "Wallabag"
        logo: "assets/tools/wallabag.png"
        subtitle: "Read-It-Later Archiver"
        tag: "read-it-later"
        url: "https://wallabag.example.com/"
        target: "_blank"
      - name: "Gitea"
        logo: "assets/tools/gitea.png"
        subtitle: "Self-hosted Git Instance"
        tag: "github"
        url: "https://gitea.example.com/"
        target: "_blank"

  - name: "Media"
    icon: "fas fa-film"
    items:
      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Media Center"
        tag: "video"
        url: "https://plex.example.com/"
        target: "_blank"
      - name: "PodGrab"
        logo: "assets/tools/podcasts-n.png"
        subtitle: "Podcasts Downloader"
        tag: "podcast"
        url: "https://podcasts.example.com/"
        target: "_blank"
      - name: "PhotoPrism: Abhilesh"
        logo: "assets/tools/photoprism.png"
        subtitle: "Photo Management and Gallery"
        tag: "photo"
        url: "https://photos.example.com/"
        target: "_blank"
      - name: "PhotoPrism: Nadya"
        logo: "assets/tools/photoprism.png"
        subtitle: "Photo Management and Gallery"
        tag: "photo"
        url: "https://gallery.example.com/"
        target: "_blank"

  - name: "Indexers"
    icon: "fas fa-magic"
    items:
      - name: "Overseerr"
        logo: "assets/tools/overseerr.png"
        subtitle: "Media Requester"
        tag: "media-requests"
        url: "https://flix.example.com/"
        target: "_blank"
      - name: "Prowlarr"
        logo: "assets/tools/prowlarr.png"
        subtitle: "Indexers Management"
        tag: "indexer manager"
        url: "https://prowlarr.example.com/"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.png"
        subtitle: "TV Show Collection Manager"
        tag: "tv-shows manager"
        url: "https://sonarr.example.com/"
        target: "_blank"
      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        subtitle: "Movie Collection Manager"
        tag: "movies manager"
        url: "https://radarr.example.com/"
        target: "_blank"
      - name: "Readarr"
        logo: "assets/tools/readarr.png"
        subtitle: "Books Collection Manager"
        tag: "books manager"
        url: "https://readarr.example.com/"
        target: "_blank"
      - name: "Lidarr"
        logo: "assets/tools/lidarr.png"
        subtitle: "Music Collection Manager"
        tag: "music manager"
        url: "https://lidarr.example.com/"
        target: "_blank"
      - name: "Bazarr"
        logo: "assets/tools/bazarr.png"
        subtitle: "Subtitles Collection Manager"
        tag: "subtitles manager"
        url: "https://bazarr.example.com/"
        target: "_blank"

  - name: "Download"
    icon: "fas fa-download"
    items:
      - name: "Tube Archivist"
        logo: "assets/tools/youtubedl.png"
        subtitle: "YouTube Downloader"
        tag: "YouTube-DL"
        url: "https://ytdl.example.com/"
        target: "_blank"
      - name: "Flood WebUI"
        logo: "assets/tools/flood.png"
        subtitle: "Beautiful WebUI for torrent clients"
        tag: "torrent webui"
        url: "https://flood.example.com/"
        target: "_blank"
      - name: "Transmission"
        logo: "assets/tools/transmission.png"
        subtitle: "Torrent Downloader"
        tag: "torrent"
        url: "https://transmission.example.com/"
        target: "_blank"
      - name: "Transmission-VPN"
        logo: "assets/tools/transmission.png"
        subtitle: "Torrent Downloader behind a VPN"
        tag: "torrent-vpn"
        url: "https://torrents.example.com/"
        target: "_blank"
      - name: "Qbittorrent-VPN"
        logo: "assets/tools/qbittorrent.png"
        subtitle: "Torrent Downloader behind a VPN"
        tag: "torrent-vpn"
        url: "https://qbittorrent.example.com/"
        target: "_blank"


  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: "AdGuard Home"
        logo: "assets/tools/adguard.png"
        subtitle: "DNS-level Ad Blocking"
        tag: "adblocker"
        url: "https://adblock.example.com/"
        target: "_blank"
      - name: "Authelia"
        logo: "assets/tools/authelia.png"
        subtitle: "SSO Authentication"
        tag: "authentication"
        url: "https://auth.example.com/"
        target: "_blank"
      - name: "Home Assistant"
        logo: "assets/tools/home-assist.png"
        subtitle: "Smart Home Management"
        tag: "home"
        url: "https://home.example.com/"
        target: "_blank"
      - name: "Gotify"
        logo: "assets/tools/gotify.png"
        subtitle: "Push Notifications Server"
        tag: "push notifications"
        url: "https://gotify.example.com/"
        target: "_blank"
      - name: "Code-Server"
        logo: "assets/tools/vscode.png"
        subtitle: "Remote VS Code Editor"
        tag: "code editor"
        url: "https://vscode.example.com/"
        target: "_blank"
      
  - name: "Server"
    icon: "fas fa-server"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Server Monitoring Dashboards" 
        tag: "monitoring"
        url: "https://status.example.com/"
        target: "_blank"
      - name: "Uptime-Kuma"
        logo: "assets/tools/uptime.png"
        subtitle: "Webservices monitor"
        tag: "uptime monitor"
        url: "https://uptime.example.com/"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Docker Container Management"
        tag: "docker"
        url: "https://portainer.example.com/"
      - name: "Nginx Proxy Manager"
        logo: "assets/tools/nginx-proxy.png"
        subtitle: "Reverse Proxy Manager"
        tag: "reverse-proxy"
        url: "https://npm.example.com/"
        target: "_blank"
